AutoService.WEB/Controllers/UserReviewsController.cs
using AutoService.WEB.Models;
using AutoService.WEB.Utils.Interfaces;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PagedList;
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AutoService.WEB.Controllers
{
    public class UserReviewsController : Controller
    {
        private ApplicationDbContext _db;
        private ApplicationUserManager _userManager;
        private IReviewsLogic _reviewsLogic;

        public UserReviewsController()
        {
        }

        public UserReviewsController(ApplicationDbContext db, IReviewsLogic logic)
        {
            _db = db;
            _reviewsLogic = logic;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: UserRewiews
        [AllowAnonymous]
        public async Task<ActionResult> Index(int? page, Messages? message)
        {
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            var userReviewsList = await _reviewsLogic.GetAllReviews();
            ViewBag.UserId = User.Identity.GetUserId();
            ViewBag.StatusMessage = MessageGenerator(message);
            return View(userReviewsList.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult CreateReview()
        {
            return PartialView("Create");
        }

        // POST: UserRewiews/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateReview(CreateReviewView userRewiew)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                var user = await UserManager.FindByIdAsync(userId);
                await _reviewsLogic.CreateReview(new UserReview(userRewiew.Text, userId, user.UserName));
                return RedirectToAction("Index", new { message = Messages.AddNewReviewSuccess });
            }
            return RedirectToAction("Index", new { message = Messages.Error });
        }

        public async Task<ActionResult> Edit(int? reviewId)
        {
            try
            {
                var userId = User.Identity.GetUserId();
                var editReviewView = await _reviewsLogic.StartEditUserReview(reviewId, userId);
                return PartialView(editReviewView);
            }
            catch (ArgumentNullException)
            {
                return RedirectToAction("Index", new { message = Messages.Error });
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Index", new { message = Messages.Error });
            }
            catch (InvalidOperationException)
            {
                return RedirectToAction("Index", new { message = Messages.Error });
            }
        }

        // POST: UserRewiews/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditUserReviewView review)
        {
            if (ModelState.IsValid)
            {
                await _reviewsLogic.EditUserReview(review);
                return RedirectToAction("Index", new { message = Messages.EditUserReviewSuccess });
            }
            return RedirectToAction("Index", new { message = Messages.Error });
        }

        // GET: UserRewiews/Delete/5
        public async Task<ActionResult> Delete(int? reviewId)
        {
            try
            {
                var userId = User.Identity.GetUserId();
                bool isAdmin = User.IsInRole("Admin");
                var review = await _reviewsLogic.StartUserReviewRemoving(reviewId, userId, isAdmin);
                return PartialView("Delete", review);
            }
            catch (ArgumentNullException)
            {
                return RedirectToAction("Index", new { message = Messages.Error });
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Index", new { message = Messages.Error });
            }
            catch (InvalidOperationException)
            {
                return RedirectToAction("Index", new { message = Messages.Error });
            }
        }

        // POST: UserRewiews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int reviewId)
        {
            await _reviewsLogic.RemoveUserReview(reviewId);
            return RedirectToAction("Index", new { message = Messages.DeleteUserReviewSuccess });
        }

        public enum Messages
        {
            AddNewReviewSuccess,
            EditUserReviewSuccess,
            DeleteUserReviewSuccess,
            Error
        }

        private string MessageGenerator(Messages? message)
        {
            return message == Messages.AddNewReviewSuccess ? "Ваш отзыв добавлен."
               : message == Messages.EditUserReviewSuccess ? "Отзыв успешно изменен."
               : message == Messages.DeleteUserReviewSuccess ? "Отзыв удален."
               : message == Messages.Error ? "Произошла ошибка."
               : null;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
                _reviewsLogic.Dispose();
                UserManager.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutoService.WEB/Views/UserReviews/Create.cshtml
@model AutoService.WEB.Models.CreateReviewView
<div class="modal-content">
    <!-- Заголовок модального окна -->
    <div class="modal-header">
        <h5 class="modal-title">Новый отзыв</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <!-- Основное содержимое модального окна -->
    @using (Html.BeginForm("CreateReview", "UserReviews", FormMethod.Post, new { @class = "validate" }))
    {
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-group ">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "col-form-label" })

            @Html.TextAreaFor(model => model.Text, new { @class = "form-control", rows = "10" })
        </div>
    </div>
    <!-- Футер модального окна -->
    <div class="modal-footer ">
        <button class="btn btn-primary" type="submit"><i class="mr-1 p-1 fa fa-send-o fa-lg"></i>Отправить</button>
        <button type="button" class="btn btn-dark" data-dismiss="modal"><i class="mr-1 p-1 fa fa-window-close fa-lg"></i>Закрыть</button>
    </div>
    }
</div>
<script>
    $('.validate').validate({
        errorClass: "text-danger",
        rules: {
            Text: {
                required: true,
                minlength: 20
            }
        },
        messages: {
            Text: {
                required: "Поле с отзывом пользователя не может быть пустым.",
                minlength: "Размер отзыва должен быть более 20 символов"
            }
        }
    });
</script>

AutoService.WEB/Views/UserReviews/Delete.cshtml
@model AutoService.WEB.Models.UserReview
    <div class="modal-content">
        <!-- Заголовок модального окна -->
        <div class="modal-header">
            <h5 class="modal-title">Вы уверенны, что хотите удалить свой отзыв?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <!-- Основное содержимое модального окна -->
        <div class="modal-body overflow-auto" style="max-height:250px">
            <div>
                <div style="min-height:150px">
                    @Html.DisplayFor(model => model.ReviewText)
                </div>
            </div>
        </div>
        <div class="text-muted text-right m-2 mr-3">
            <label><i class="fa fa-calendar mr-1 p-1"></i>Дата: </label>
            @Model.DateOfCreation.ToShortDateString()
        </div>
        <div class="modal-footer">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <button type="submit" class="btn btn-outline-danger"><i class="fa fa-trash mr-1 p-1"></i>Удалить</button>
                <button type="button" class="btn btn-outline-dark" data-dismiss="modal"><i class="fa fa-window-close mr-1 p-1"></i>Закрыть</button>
            }
        </div>
    </div>

AutoService.WEB/Views/UserReviews/Edit.cshtml
@model AutoService.WEB.Models.EditUserReviewView
<div class="modal-content">
    <!-- Заголовок модального окна -->
    <div class="modal-header">
        <h5 class="modal-title">Новый отзыв</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <!-- Основное содержимое модального окна -->
    @using (Html.BeginForm("Edit", "UserReviews", FormMethod.Post, new { @class = "validate" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ReviewId)
        <div class="modal-body">
            <div class="form-group ">
                @Html.LabelFor(model => model.EditedText, htmlAttributes: new { @class = "col-form-label" })

                @Html.TextAreaFor(model => model.EditedText, new { @class = "form-control", rows = "10" })
            </div>
        </div>
        <!-- Футер модального окна -->
        <div class="modal-footer ">
            <button class="btn btn-primary" type="submit"><i class="mr-1 p-1 fa fa-save fa-lg"></i>Сохранить</button>
            <button type="button" class="btn btn-dark" data-dismiss="modal"><i class="mr-1 p-1 fa fa-window-close fa-lg"></i>Закрыть</button>
        </div>
    }
</div>
<script>
    $('.validate').validate({
        errorClass: "text-danger",
        rules: {
            EditedText: {
                required: true,
                minlength: 20
            }
        },
        messages: {
            EditedText: {
                required: "Поле с отзывом пользователя не может быть пустым.",
                minlength: "Размер отзыва должен быть более 20 символов"
            }
        }
    });
</script>

AutoService.WEB/Views/UserReviews/Index.cshtml
@model PagedList.IPagedList<AutoService.WEB.Models.UserReview>
@using PagedList.Mvc
@{
    ViewBag.Title = "Отзывы пользователей";
}
<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>

@if (ViewBag.StatusMessage != null)
{
    string message = ViewBag.StatusMessage as string;
    message.ToLower();
    if (!message.Contains("ошибка"))
    {
        @Html.Partial("SuccessOperation")
    }
    else
    {
        @Html.Partial("ErrorModalView")
    }

}
@if (Model.Count > 0)
{
    <h2 class="text-center m-2 mt-3">
        Отзывы пользователей
        @if (User.Identity.IsAuthenticated)
        {
            <a class="dialog btn btn-outline-success btn-sm" title="Добавить отзыв" href="@Url.Action("CreateReview")">
                <i class="fa fa-plus"></i>
            </a>
        }
    </h2>
    <div class="row row-cols-1 justify-content-center ">
        @foreach (var review in Model)
        {
            @Html.Partial("UserReviewItem", review)
        }
    </div>
    <div>
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </div>
}
else
{
    <h2 class="text-center m-2 mt-3">Пусто</h2>
}

@section scripts
{
    @Scripts.Render("~/scripts/InvokeModalDialog.js")
    @Scripts.Render("~/scripts/jquery.validate.min.js")
    <script>
        $(window).on('load', function () {
            $('#statusMessage').modal('show');
        });
    </script>
}

AutoService.WEB/Views/UserReviews/UserReviewItem.cshtml
@using AutoService.WEB.Models
@model UserReview

<div class="col-sm-12 col-xl-6 col-md-8 m-3">
    <div class="card rounded shadow-sm">
        <div class="card-header bg-dark text-center text-white"><i class="fa fa-user-o mr-1 p-1"></i>Автор:  @Model.UserName</div>
        <div class="card-body" style="min-height:150px">
            <div class="card-text">
                @Model.ReviewText
            </div>
        </div>
        <div class="text-muted text-right p-2">
            <label class="mr-1"><i class="fa fa-calendar fa-lg p-1 mr-1"></i>Дата:</label>@Model.DateOfCreation.ToShortDateString()
        </div>
        @if (User.IsInRole("Admin"))
        {
            <div class="card-footer text-center">
                <a style="width:110px" class="dialog btn btn-dark btn-sm" href="@Url.Action("Delete", new { reviewId = Model.UserReviewId })">
                    <i class="fa fa-trash mr-1 p-1"></i>Удалить
                </a>
            </div>
        }
        else if (Model.OwnerId == ViewBag.UserId)
        {
            <div class="card-footer text-center">
                <a style="width:110px" class="dialog btn btn-dark btn-sm" href="@Url.Action("Delete", new { reviewId = Model.UserReviewId })">
                    <i class="fa fa-trash mr-1 p-1"></i>Удалить
                </a>
                <a style="width:110px" class="dialog btn btn-dark btn-sm" href="@Url.Action("Edit", new { reviewId = Model.UserReviewId })">
                    <i class="fa fa-pencil-square-o mr-1 p-1"></i>Изменить
                </a>
            </div>
        }
    </div>
</div>