AutoService.WEB/Controllers/NewsPageController.cs
using AutoService.WEB.Models;
using AutoService.WEB.Utils.Interfaces;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AutoService.WEB.Controllers
{
    public class NewsPageController : Controller
    {
        private INewsPageLogic _newsPageLogic;

        public NewsPageController(INewsPageLogic newsPageLogic)
        {
            _newsPageLogic = newsPageLogic;
        }

        public NewsPageController()
        {
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index(Message? message)
        {
            ViewBag.StatusMessage = MessageGenerator(message);
            var news = await _newsPageLogic.GetAllNews();
            return View(news);
        }

        public enum Message
        {
            createSuccess,
            removeSuccess,
            editSuccess,
            error
        }

        private string MessageGenerator(Message? message)
        {
            return message == Message.createSuccess ? "Новость успешно создана"
                : message == Message.editSuccess ? "Новость обновлена"
                : message == Message.removeSuccess ? "Новость успешно удалена"
                : message == Message.error ? "Произошла ошибка"
                : null;
        }

        public async Task<ActionResult> GetNews(int? newsId)
        {
            try
            {
                var news = await _newsPageLogic.GetNews(newsId);
                return View("UserNewsView", news);
            }
            catch (ArgumentNullException)
            {
                return RedirectToAction("Index", new { message = Message.error });
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Index", new { message = Message.error });
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult CreateNews()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateNews(CreateNews news)
        {
            if (ModelState.IsValid)
            {
                await _newsPageLogic.AddNews(news);
                return RedirectToAction("Index", new { message = Message.createSuccess });
            }
            return RedirectToAction("Index", new { message = Message.error });
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> RemoveNews(int? newsId)
        {
            try
            {
                var news = await _newsPageLogic.GetNews(newsId);
                return PartialView(news);
            }
            catch (ArgumentNullException)
            {
                return RedirectToAction("Index", new { message = Message.error });
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Index", new { message = Message.error });
            }
        }

        [HttpPost, ActionName("RemoveNews")]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveNewsConfirmed(int newsId)
        {
            if (ModelState.IsValid)
            {
                _newsPageLogic.RemoveNews(newsId);
                return RedirectToAction("Index", new { message = Message.removeSuccess });
            }
            return RedirectToAction("Index", new { message = Message.error });
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> EditNews(int? newsId)
        {
            try
            {
                var news = await _newsPageLogic.StartEditNews(newsId);
                return View(news);
            }
            catch (ArgumentNullException)
            {
                return RedirectToAction("Index", new { message = Message.error });
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Index", new { message = Message.error });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditNews(EditNews news)
        {
            if (ModelState.IsValid)
            {
                await _newsPageLogic.EditNews(news);
                return RedirectToAction("Index", new { message = Message.editSuccess });
            }
            return View(news);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

AutoService.WEB/Controllers/ServicesController.cs
using AutoService.WEB.Models;
using AutoService.WEB.Utils.Interfaces;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AutoService.WEB.Controllers
{
    public class ServicesController : Controller
    {
        private ApplicationDbContext _db;
        private IServicesLogic _servicesLogic;

        public ServicesController()
        {
        }

        public ServicesController(ApplicationDbContext db, IServicesLogic servicesLogic)
        {
            _db = db;
            _servicesLogic = servicesLogic;
        }

        // GET: Services
        [AllowAnonymous]
        public async Task<ActionResult> Index(Messages? message)
        {
            var services = await _servicesLogic.GetAllServices();
            ViewBag.StatusMessage = MessageGenerator(message);
            return View(services);
        }

        public enum Messages
        {
            UpdateSucces,
            CreateNewServiceSucces,
            DeleteSuccess,
            Error
        }

        private string MessageGenerator(Messages? message)
        {
            return message == Messages.UpdateSucces ? "Услуга успешно обновлена"
                : message == Messages.UpdateSucces ? "Новая услуга успешно создана"
                : message == Messages.DeleteSuccess ? "Услуга успешно удалена"
                : message == Messages.Error ? "Ошибка"
                : null;
        }

        // GET: Services/Create
        public ActionResult Create()
        {
            return PartialView("AddNewService");
        }

        // POST: Services/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ServiceView serviceView)
        {
            if (ModelState.IsValid)
            {
                var service = new Service(serviceView.ServiceName, serviceView.Price, serviceView.ServiceImageHref);
                await _servicesLogic.AddNewService(service);
                return RedirectToAction("Index", new { message = Messages.CreateNewServiceSucces });
            }
            return View(serviceView);
        }

        // GET: Services/Edit/5
        public async Task<ActionResult> Edit(int? serviceId)
        {
            try
            {
                var service = await _servicesLogic.FindService(serviceId);
                var editServiceView = new EditServiceView(service.ServiceId, service.ServiceName, service.Price, service.ServiceImageHref);
                return PartialView(editServiceView);
            }
            catch (ArgumentNullException)
            {
                return RedirectToAction("Index", new { message = Messages.Error });
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Index", new { message = Messages.Error });
            }
        }

        // POST: Services/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditServiceView service)
        {
            if (ModelState.IsValid)
            {
                await _servicesLogic.EditService(service);
                return RedirectToAction("Index", new { message = Messages.UpdateSucces });
            }
            return View(service);
        }

        // GET: Services/Delete/5
        public async Task<ActionResult> Delete(int? serviceId)
        {
            try
            {
                var service = await _servicesLogic.FindService(serviceId);
                return PartialView(service);
            }
            catch (ArgumentNullException)
            {
                return RedirectToAction("Index", new { message = Messages.Error });
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Index", new { message = Messages.Error });
            }
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int serviceId)
        {
            await _servicesLogic.RemoveService(serviceId);
            return RedirectToAction("Index", new { message = Messages.DeleteSuccess });
        }

        public async Task<ActionResult> SearchServicesByName(string serviceName)
        {
            var services = await _servicesLogic.SearchServicesByName(serviceName);
            if (services.Count <= 0)
            {
                return RedirectToAction("Index", new { message = Messages.Error });
            }
            return PartialView("ServicesSearch", services);
        }

        public async Task<ActionResult> GetServicesSortedByDiscount()
        {
            var sortedServices = await _servicesLogic.GetServicesSortedByDiscount();
            return PartialView("SortedServices", sortedServices);
        }

        public async Task<ActionResult> GetServicesSortedByPrice()
        {
            var sortedServices = await _servicesLogic.GetServicesSortedByPrice();
            return PartialView("SortedServices", sortedServices);
        }

        public async Task<ActionResult> GetAllServices()
        {
            var services = await _servicesLogic.GetAllServices();
            return PartialView("SortedServices", services);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutoService.WEB/Views/Shared/DisplayEmail.cshtml
@{
    ViewBag.Title = "Завершение регистрации";
}

    <div class="mx-auto text-center mt-3">
        <h2 class="mb-2">@ViewBag.Title</h2>
        <h4>На указанный электронный адрес отправлены дальнейшие инструкции по завершению регистрации</h4>
        <div class="d-flex m-2">
            <img class="img-fluid mx-auto" height="450" width="450" src="https://sm.ign.com/ign_ru/news/h/how-long-c/how-long-could-you-actually-survive-in-fallout_48vg.png" alt="Alternate Text" />
        </div>
        <div class="text-center">
            <a class="btn btn-dark btn-lg m-2" href="@Url.Action("Index","Home")"><i class="fa fa-home mr-1 p-1"></i> На главную</a>
        </div>
    </div>

AutoService.WEB/Views/Shared/ErrorModalView.cshtml
<div class="modal fade" id="statusMessage">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-danger">
                <h5 class="modal-title">Оповещение системы</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <img class="img-fluid" width="450" height="450" src="https://i.imgur.com/AIONMn0.png" />
                <p class="text-center m-2" style="font-size:20px">@ViewBag.StatusMessage</p>
            </div>
            <div class="modal-footer bg-danger">
                <button type="button" class="btn btn-outline-dark" data-dismiss="modal"><i class="fa fa-window-close fa-lg mr-1 p-1"></i>Закрыть</button>
            </div>
        </div>
    </div>
</div>

AutoService.WEB/Views/Shared/Info.cshtml
@{
    ViewBag.Title = "Info";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<a class="btn btn-info" href="@TempData["ViewBagLink"]">Подтверждение почты</a>

AutoService.WEB/Views/Shared/SuccessOperation.cshtml
<div class="modal fade" id="statusMessage">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-success">
                <h5 class="modal-title">Оповещение системы</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="d-flex">
                    <img class="img-fluid mx-auto" width="350" height="350" src="https://vignette.wikia.nocookie.net/fallout/images/c/c0/VaultBoyFO3.png/revision/latest?cb=20110809182235" />
                </div>
                <div class="text-center m-1 p-1" style="font-size:20px">@ViewBag.StatusMessage</div>
            </div>
            <div class="modal-footer bg-success">
                <button type="button" class="btn btn-outline-dark" data-dismiss="modal"><i class="fa fa-window-close fa-lg mr-1 p-1"></i>Закрыть</button>
            </div>
        </div>
    </div>
</div>

AutoService.WEB/Views/Shared/SuccessView.cshtml
<!-- HTML-код модального окна -->

<div class="modal-content">
    <!-- Заголовок модального окна -->
    <div class="modal-header">
        <h5 class="modal-title">Сообщение</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <!-- Основное содержимое модального окна -->
    <div class="modal-body">
        Товар успешно добавлен в корзину.
    </div>
    <!-- Футер модального окна -->
    <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Закрыть</button>
    </div>
</div>

AutoService.WEB/Views/Shared/Test.cshtml
@using AutoService.WEB.Models
@model EditCarView

    <div>
        <p>@Model.UserName</p>
        <p>@Model.Email</p>
        <p>@Model.Phone</p>
        <p>@Model.Age</p>
    </div>

AutoService.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark p-3 ">
        <a class="navbar-brand" href="/">
            AutoService
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @Html.ActionLink("Главная", "Index", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Услуги", "Index", "Services", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Вакансии", "Index", "Vacancies", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Контакты", "Index", "ContactInfo", null, new { @class = "nav-link" })
                </li>
                <li>
                    @Html.ActionLink("Отзывы", "Index", "UserReviews", null, new { @class = "nav-link" })
                </li>
                @if (User.IsInRole("Admin"))
                {
                    <li>
                        <a class="nav-link" href="@Url.Action("Index","NewsPage")">Новости</a>
                    </li>
                }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>
    <div class="container-fluid" style="min-height:100%">
        @RenderBody()
    </div>
    <!-- Footer -->
    <footer class="bg-dark text-center p-2 text-white">
        &copy;2019 - 2020 Все права защищены.
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        $(window).on('load', function () {
            $("#counter").load("ShopCart/ShopCartItemsCounter")
        });
    </script>
    <script>
        $(".addToCart").click(function () {
            setTimeout(function () {
                $.ajax({
                    url: "ShopCart/ShopCartItemsCounter",
                    method: "GET",
                    success: function (data) {
                        $("#counter").text(data)
                    }
                })
            }, 1000)
        })
    </script>
</body>
</html>