AutoService.WEB/Models/HomeViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AutoService.WEB.Models
{
    public class HomeView
    {
        public List<CarBrand> CarBrands { get; set; }
        public List<ServiceView> Discounts { get; set; }
        public List<Slide> HomeMainCarouselItems { get; set; }
    }

    public class CarBrand
    {
        [Key]
        public int BrandId { get; set; }

        public string BrandName { get; set; }
        public string ImageHref { get; set; }
    }
}

AutoService.WEB/Controllers/HomeController.cs
using AutoService.WEB.Models;
using AutoService.WEB.Utils.Interfaces;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AutoService.WEB.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {
        private ApplicationDbContext _db;
        private IHomePageLogic _homePageLogic;

        public HomeController(ApplicationDbContext db, IHomePageLogic homePageLogic)
        {
            _db = db;
            _homePageLogic = homePageLogic;
        }

        public async Task<ActionResult> Index()
        {
            HomeView homeView = new HomeView()
            {
                CarBrands = await _homePageLogic.GetCarBrandsCarousel(),
                Discounts = await _homePageLogic.GetRelevantDiscountsForHomePage(),
                HomeMainCarouselItems = await _homePageLogic.GetMainCarousel()
            };
            return View(homeView);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
                _homePageLogic.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutoService.WEB/Controllers/NewsPageController.cs
using AutoService.WEB.Models;
using AutoService.WEB.Utils.Interfaces;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AutoService.WEB.Controllers
{
    public class NewsPageController : Controller
    {
        private INewsPageLogic _newsPageLogic;

        public NewsPageController(INewsPageLogic newsPageLogic)
        {
            _newsPageLogic = newsPageLogic;
        }

        public NewsPageController()
        {
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index(Message? message)
        {
            ViewBag.StatusMessage = MessageGenerator(message);
            var news = await _newsPageLogic.GetAllNews();
            return View(news);
        }

        public enum Message
        {
            createSuccess,
            removeSuccess,
            editSuccess,
            error
        }

        private string MessageGenerator(Message? message)
        {
            return message == Message.createSuccess ? "Новость успешно создана"
                : message == Message.editSuccess ? "Новость обновлена"
                : message == Message.removeSuccess ? "Новость успешно удалена"
                : message == Message.error ? "Произошла ошибка"
                : null;
        }

        public async Task<ActionResult> GetNews(int? newsId)
        {
            try
            {
                var news = await _newsPageLogic.GetNews(newsId);
                return View("UserNewsView", news);
            }
            catch (ArgumentNullException)
            {
                return RedirectToAction("Index", new { message = Message.error });
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Index", new { message = Message.error });
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult CreateNews()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateNews(CreateNews news)
        {
            if (ModelState.IsValid)
            {
                await _newsPageLogic.AddNews(news);
                return RedirectToAction("Index", new { message = Message.createSuccess });
            }
            return RedirectToAction("Index", new { message = Message.error });
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> RemoveNews(int? newsId)
        {
            try
            {
                var news = await _newsPageLogic.GetNews(newsId);
                return PartialView(news);
            }
            catch (ArgumentNullException)
            {
                return RedirectToAction("Index", new { message = Message.error });
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Index", new { message = Message.error });
            }
        }

        [HttpPost, ActionName("RemoveNews")]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveNewsConfirmed(int newsId)
        {
            if (ModelState.IsValid)
            {
                _newsPageLogic.RemoveNews(newsId);
                return RedirectToAction("Index", new { message = Message.removeSuccess });
            }
            return RedirectToAction("Index", new { message = Message.error });
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> EditNews(int? newsId)
        {
            try
            {
                var news = await _newsPageLogic.StartEditNews(newsId);
                return View(news);
            }
            catch (ArgumentNullException)
            {
                return RedirectToAction("Index", new { message = Message.error });
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Index", new { message = Message.error });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditNews(EditNews news)
        {
            if (ModelState.IsValid)
            {
                await _newsPageLogic.EditNews(news);
                return RedirectToAction("Index", new { message = Message.editSuccess });
            }
            return View(news);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

AutoService.WEB/Controllers/ShopCartController.cs
using AutoService.WEB.Models;
using AutoService.WEB.Utils.Interfaces;
using Microsoft.AspNet.Identity;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AutoService.WEB.Controllers
{
    [Authorize]
    public class ShopCartController : Controller
    {
        private IServicesLogic _serviceLogic;
        private ISummariesLogic _summariesLogic;
        private ICarLogic _carLogic;

        public ShopCartController(IServicesLogic serviceLogic, ISummariesLogic summariesLogic, ICarLogic carLogic)
        {
            _serviceLogic = serviceLogic;
            _summariesLogic = summariesLogic;
            _carLogic = carLogic;
        }

        public ActionResult Index(Cart cart, SystemMessages? message)
        {
            var view = new CartIndexViewModel()
            {
                Cart = cart
            };
            ViewBag.StatusMessage = MessageGenerator(message);
            return View(view);
        }

        public enum SystemMessages
        {
            removeFromCartSuccess,
            cleanUpShopCartSuccess,
            orderCreateSuccess,
            Error
        }

        private string MessageGenerator(SystemMessages? message)
        {
            return message == SystemMessages.Error ? "Произошла ошибка"
                : message == SystemMessages.cleanUpShopCartSuccess ? "Корзина очищена"
                : message == SystemMessages.orderCreateSuccess ? "Заказ успешно создан"
                : message == SystemMessages.removeFromCartSuccess ? "Услуга удалена из корзины"
                : null;
        }

        public async Task<ActionResult> AddToCart(Cart cart, int? serviceId)
        {
            try
            {
                var service = await _serviceLogic.FindServiceWithDiscount(serviceId);
                cart.AddItem(service);
                return PartialView("AddToCartModalView");
            }
            catch (ArgumentNullException)
            {
                return RedirectToAction("Index", new { message = SystemMessages.Error });
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Index", new { message = SystemMessages.Error });
            }
            catch (Exception)
            {
                return PartialView("ExistsInUserShopCartModalView");
            }
        }

        public async Task<ActionResult> RemoveFromCart(int? serviceId)
        {
            try
            {
                var service = _serviceLogic.MapServiceToServiceView(await _serviceLogic.FindServiceWithDiscount(serviceId));
                return PartialView("DeleteServiceFromShopCartModalView", service);
            }
            catch (ArgumentNullException)
            {
                return RedirectToAction("Index", new { message = SystemMessages.Error });
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Index", new { message = SystemMessages.Error });
            }
        }

        [HttpPost, ActionName("RemoveFromCart")]
        public ActionResult RemoveFromCartConfirmed(Cart cart, int? serviceId)
        {
            if (ModelState.IsValid)
            {
                cart.RemoveFromCart(serviceId);
                return RedirectToAction("Index", new { message = SystemMessages.removeFromCartSuccess });
            }
            return RedirectToAction("Index", new { message = SystemMessages.Error });
        }

        public ActionResult ClearShopCart()
        {
            return PartialView();
        }

        [HttpPost, ActionName("ClearShopCart")]
        public ActionResult ClearShopCartConfirmed(Cart cart)
        {
            cart.Clear();
            return RedirectToAction("Index", new { message = SystemMessages.cleanUpShopCartSuccess });
        }

        public async Task<ActionResult> GetServiceSummary(Cart cart)
        {
            var userId = User.Identity.GetUserId();
            var userCars = await _carLogic.GetAllUserCars(userId);
            ViewBag.Cars = new SelectList(userCars, "CarId", "FullName");
            var summary = _summariesLogic.GetServicesSummaryView(cart.Lines, cart.ComputeTotalValue());
            return View("ServicesSummary", summary);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> GetServiceSummary(ServicesSummaryView summary, Cart cart)
        {
            var userId = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                ServicesSummary servicesSummary = new ServicesSummary()
                {
                    DateOfCreating = DateTime.Now,
                    DayOfWork = summary.selectedDateTime,
                    TotalPrice = summary.TotalPrice,
                    UserCarId = summary.CarId,
                    UserId = userId,
                    ServiceList = _serviceLogic.ServicesToString(cart.Lines.ToList())
                };
                await _summariesLogic.AddNewSummary(servicesSummary);
                cart.Clear();
                return RedirectToAction("Index", new { message = SystemMessages.orderCreateSuccess });
            }
            return RedirectToAction("Index", new { message = SystemMessages.Error });
        }

        public int ShopCartItemsCounter(Cart cart)
        {
            return cart.ShopCartItemsCounter();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _carLogic.Dispose();
                _serviceLogic.Dispose();
                _summariesLogic.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutoService.WEB/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AutoService.WEB/Views/Home/BrandCarousel.cshtml
@model IEnumerable<AutoService.WEB.Models.CarBrand>
    <div class="mx-auto col-xl-12 p-0 mb-3">
        <div class="card shadow-sm">
            <div class="card-header text-white bg-dark text-center"><h5>Марки с которыми мы работаем</h5></div>
            <div class="card-body pb-1">
                <div class="owl-carousel owl-theme">
                    @foreach (var brand in Model)
                    {
                        <div class="m-2">
                            <img src="@brand.ImageHref" alt="@brand.BrandName" title="@brand.BrandName" />
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

AutoService.WEB/Views/Home/DiscountCarousel.cshtml
@model List<AutoService.WEB.Models.ServiceView>

<!--Карточка Акции-->
<div class="col-xl-4 mx-auto m-2">
    <div class="card rounded h-100" style="max-height:580px">
        <div class="card-header bg-dark text-white text-center h5">
            Акции
        </div>
        <div class="card-body p-1 pr-2 pl-2 align-items-center d-flex">
            <div id="DiscountCarousel" class="carousel slide w-100" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item h-100 active">
                        @Html.Partial("HomePageDiscountsitemView", Model[0])
                    </div>
                    @for (int i = 1; i < Model.Count(); i++)
                    {
                        <div class="carousel-item h-100">
                            @Html.Partial("HomePageDiscountsitemView", Model[i])
                        </div>
                    }
                </div>
                <!-- Элементы управления -->
                <a class="carousel-control-prev" href="#DiscountCarousel" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Предыдущий</span>
                </a>
                <a class="carousel-control-next" href="#DiscountCarousel" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Следующий</span>
                </a>
            </div>
        </div>
    </div>
</div>

AutoService.WEB/Views/Home/HomePageDiscountsitemView.cshtml
@model AutoService.WEB.Models.ServiceView
<div class="card mx-auto h-100" style="max-width:480px;min-height:420px">
    <div class="h-50">
        <img class="card-img" src="@Model.ServiceImageHref" alt="@Model.ServiceName" style="max-height:250px" />
    </div>
    <div class="h-50">
        <div class="h5 bg-dark text-white text-center p-2">
            @if (Model.Discount == null)
            {
                @Model.ServiceName
            }
            else if (Model.Discount.isRelevant())
            {
                if (Model.Discount.Value <= 30)
                {
                    @Model.ServiceName <span class="badge badge-success">-@Model.Discount.Value%</span>
                }
                else if (Model.Discount.Value > 30 && Model.Discount.Value < 60)
                {
                    @Model.ServiceName <span class="badge badge-warning">-@Model.Discount.Value%</span>
                }
                else
                {
                    @Model.ServiceName <span class="badge badge-danger">-@Model.Discount.Value%</span>
                }
            }
            else
            {
                @Model.ServiceName
            }
        </div>
        <div class="card-body text-center p-1">
            <div>
                <div>
                    <label class="mr-1">Цена:</label>@Model.PriceWithDiscount<i class="fa fa-rub p-1"></i> (Выгода:@(Model.Price-Model.PriceWithDiscount)<i class="fa fa-rub p-1"></i>)
                </div>
                @if (User.Identity.IsAuthenticated && !User.IsInRole("Admin"))
                {
                    <a class="dialog btn btn-dark btn-sm addToCart mx-auto" href="@Url.Action("AddToCart","ShopCart",new { serviceId = Model.ServiceId })" title="Добавить в корзину">
                        <i class="fa fa-shopping-cart"></i>+
                    </a>
                }
            </div>
        </div>
        <div class="card-footer bg-transparent border-0 p-1">
            <div class="input-group text-center">
                <div class="input-group-prepend">
                    <div class="input-group-text">
                        <i class="fa fa-calendar"></i>
                    </div>
                </div>
                <div class="form-control">
                    @Model.Discount.StartDate.ToShortDateString() - @Model.Discount.FinishDate.ToShortDateString()
                </div>
            </div>
        </div>
    </div>
</div>

AutoService.WEB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная";
}
@model AutoService.WEB.Models.HomeView

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>

<div class="row mt-3 mb-3">
    <!--Главная карусель-->
    @Html.Partial("MainCarousel", Model.HomeMainCarouselItems)
    <!--БлокСкидки-->
    @if (Model.Discounts.Count > 0)
    {
        @Html.Partial("DiscountCarousel", Model.Discounts)
    }
</div>
<!--Автобренды-->

@Html.Partial("BrandCarousel", Model.CarBrands)
@section Scripts {
    @Scripts.Render("~/scripts/InvokeModalDialog.js")
    @Scripts.Render("~/scripts/owl.carousel.js")
    @Scripts.Render("~/scripts/Script.js")
}

AutoService.WEB/Views/Home/MainCarousel.cshtml
@model List<AutoService.WEB.Models.Slide>

<div class="mx-auto col-xl-8 m-2">
    <div id="carousel" class="carousel slide h-100" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active myCarouselItem">
                <a href="@Url.Action("GetNews","NewsPage", new { newsId = Model[0].NewsId})"><img class="mx-auto d-block img-fluid w-100 myCarouselItem rounded" src="@Model[0].ImgHref" alt="Image" title="@Model[0].SlideTitle"></a>
                <div class="carousel-caption">
                    <h5>@Model[0].SlideTitle</h5>
                    <p>@Model[0].SlideDescription</p>
                </div>
            </div>
            @for (int i = 1; i < Model.Count; i++)
            {
        <div class="carousel-item myCarouselItem">
            <a href="@Url.Action("GetNews","NewsPage", new { newsId = Model[i].NewsId})"><img class="mx-auto d-block img-fluid w-100 myCarouselItem rounded" src="@Model[i].ImgHref" alt="Image" title="@Model[0].SlideTitle"></a>
            <div class="carousel-caption">
                <h5>@Model[i].SlideTitle</h5>
                <p>@Model[i].SlideDescription</p>
            </div>
        </div>
            }
        </div>
        @if (Model.Count > 1)
        {
            <!-- Элементы управления -->
            <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Предыдущий</span>
            </a>
            <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Следующий</span>
            </a>
        }
    </div>
</div>

AutoService.WEB/Views/Home/PopularServices.cshtml
<div class="row row-cols-4 row-cols-xl-3 row-cols-sm-1 row-cols-md-2 col-lg-10 col-md-11 col-sm-11 ml-auto mr-auto mt-2 border border-dark p-2 d-flex ">

    @foreach (var service in Model.PopularServices)
        {
    <div class="col-md-3 col-sm-6 mt-2 mb-2 text-center bg-light p-0 mr-xl-auto ml-xl-auto ml-auto mr-auto" style="max-width:350px; min-width:250px">
        <div class="image position-relative overflow-hidden">
            <img class="w-100" src="@service.ServiceImageHref" alt="..." height="200">
        </div>
        <div class="p-2">
            <h3 class="title" style="height: 72px;">
                @if (service.Discount == null)
                        {
                @service.ServiceName
                        }
                        else if (service.Discount.Value <= 20)
                        {
                @service.ServiceName  <span class="badge badge-success">-@service.Discount.Value%</span>
                        }
                        else if (service.Discount.Value > 20 && service.Discount.Value < 70)
                        {
                @service.ServiceName  <span class="badge badge-warning">-@service.Discount.Value%</span>
                        }
                        else
                        {
                @service.ServiceName  <span class="badge badge-danger">-@service.Discount.Value%</span>
                        }
            </h3>
            <div class="text" style="height: 52px;">
                Brakes wear out over time requiring service
            </div>
        </div>
    </div>
        }
</div>