AutoService.WEB/Controllers/ContactInfoController.cs
using AutoService.WEB.Models;
using AutoService.WEB.Utils.Interfaces;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AutoService.WEB.Controllers
{
    public class ContactInfoController : Controller
    {
        // GET: ContactInfo

        private IContactInfoLogic _contactInfoLogic;

        public ContactInfoController()
        {
        }

        public ContactInfoController(IContactInfoLogic logic)
        {
            _contactInfoLogic = logic;
        }

        public async Task<ActionResult> Index()
        {
            var contactView = await _contactInfoLogic.getContactView();
            return View(contactView);
        }

        public enum Messages
        {
            Error,
            AddNewInfoSucces,
            RemoveInfoSuccess,
            SwitchSuccess
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AddNewInfo()
        {
            ViewBag.Types = new SelectList(_contactInfoLogic.GetContactItemsTypes(), "type");
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddNewInfo(AddNewContactView newContactItem)
        {
            if (ModelState.IsValid)
            {
                await _contactInfoLogic.AddItem(newContactItem);
                return RedirectToAction("EditContacts", new { message = Messages.AddNewInfoSucces });
            }
            return RedirectToAction("EditContacts", new { message = Messages.Error });
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> EditContacts(Messages? message)
        {
            ViewBag.StatusMessage = MessageGenerator(message);
            EditContactInformationView view = await _contactInfoLogic.GetEditContactInformationView();
            return View(view);
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> SwitchStatus(int? itemId)
        {
            try
            {
                await _contactInfoLogic.SwitchStatus(itemId);
                return RedirectToAction("EditContacts", new { message = Messages.SwitchSuccess });
            }
            catch (ArgumentNullException)
            {
                return RedirectToAction("EditContacts", new { message = Messages.Error });
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("EditContacts", new { message = Messages.Error });
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> RemoveItem(int? itemId)
        {
            try
            {
                var contactItem = await _contactInfoLogic.FindItem(itemId);
                return PartialView("RemoveItemModalView", contactItem);
            }
            catch (ArgumentNullException)
            {
                return RedirectToAction("EditContacts", new { message = Messages.Error });
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("EditContacts", new { message = Messages.Error });
            }
        }

        [HttpPost, ActionName("RemoveItem")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemoveConfirmed(int itemId)
        {
            try
            {
                await _contactInfoLogic.RemoveItem(itemId);
                return RedirectToAction("EditContacts", new { message = Messages.RemoveInfoSuccess });
            }
            catch (ArgumentNullException)
            {
                return RedirectToAction("EditContacts", new { message = Messages.Error });
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("EditContacts", new { message = Messages.Error });
            }
        }

        private string MessageGenerator(Messages? message)
        {
            return message == Messages.AddNewInfoSucces ? "Информация добавлена"
               : message == Messages.RemoveInfoSuccess ? "Информация удалена"
               : message == Messages.Error ? "Ошибка"
               : message == Messages.SwitchSuccess ? "Статус изменен"
               : null;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _contactInfoLogic.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutoService.WEB/Views/ContactInfo/AddNewInfo.cshtml
@using AutoService.WEB.Models
@model AddNewContactView
@{
    ViewBag.Title = "Добавление новой контактной информации";
}
<div class="modal-content">
    <!-- Заголовок модального окна -->
    <div class="modal-header">
        <h5 class="modal-title">Контактная информация</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <!-- Основное содержимое модального окна -->
    @using (Html.BeginForm("AddNewInfo", "ContactInfo", null, FormMethod.Post, new { @class = "validate" }))
    {
        @Html.AntiForgeryToken()
        <div class="modal-body">
            <div class="form-group">
                <label class="col-form-label">Тип информации:</label>
                @Html.DropDownListFor(model => model.Type, ViewBag.Types as SelectList, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label class="col-form-label">Данные:</label>
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <!-- Футер модального окна -->
        <div class="modal-footer ">
            <button class="btn btn-outline-dark" type="submit"><i class="mr-1 p-1 fa fa-send"></i>Добавить</button>
            <button type="button" class="btn btn-dark" data-dismiss="modal"><i class="mr-1 p-1 fa fa-window-close fa-lg"></i>Закрыть</button>
        </div>
    }
</div>
<script>
    $('.validate').validate({
        errorClass: "text-danger",
        rules: {
            Value: {
                required: true
            },
            Type: {
                required: true
            }
        },
        messages: {
            Value: {
                required: "Данное поле не может быть пустым"
            },
            Type: {
                required: "Данное поле не может быть пустым"
            }
        }
    });
</script>

AutoService.WEB/Views/ContactInfo/ContactItemView.cshtml
@model AutoService.WEB.Models.ContactItem
<div class="card rounded m-2" style="max-width:250px;width:250px">
    <div class="card-header bg-dark text-white">
        <h5 class="text-center">
            @Model.Name
    </h5>
</div>
<div class="card-body text-center">
    <div>
        @Model.Value
    </div>
</div>
<div class="card-footer text-center">
    <a class="btn btn-danger btn-sm dialog" href="@Url.Action("RemoveItem","ContactInfo", new { itemId = Model.Id })"><i class="fa fa-trash mr-1 p-1"></i>Удалить</a>
    @if (Model.isActive)
    {
        <a class="btn btn-secondary btn-sm" href="@Url.Action("SwitchStatus","ContactInfo", new { itemId = Model.Id })"><i class="fa fa-power-off mr-1 p-1"></i>Выкл</a>
    }
    else
    {
        <a class="btn btn-success btn-sm" href="@Url.Action("SwitchStatus","ContactInfo", new { itemId = Model.Id })"><i class="fa fa-power-off mr-1 p-1"></i>Вкл</a>
    }
</div>
</div>

AutoService.WEB/Views/ContactInfo/EditContacts.cshtml
@using AutoService.WEB.Models
@model EditContactInformationView
@{
    ViewBag.Title = "Изменение контактной информации";
}

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>
@if (ViewBag.StatusMessage != null)
{
    string message = ViewBag.StatusMessage as string;
    if (!message.Contains("Ошибка"))
    {
        @Html.Partial("SuccessOperation")
    }
    else
    {
        @Html.Partial("ErrorModalView")
    }

}
<div class="col-xl-7 col-md-8 col-sm-10 mx-auto mt-4 mb-4 p-0">
    <div class="card rounded shadow-sm">
        <h4 class="card-header bg-dark text-center text-white">Контактная информация <a class="btn btn-primary dialog btn-sm" href="@Url.Action("AddNewInfo")"><i class="fa fa-plus"></i></a></h4>
        <div class="card-body">
            <div class="row justify-content-center">
                @foreach (var item in Model.ContactItems)
                {
                    @Html.Partial("ContactItemView", item)
                }
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/scripts/InvokeModalDialog.js")
    @Scripts.Render("~/scripts/jquery.validate.min.js")
    <script>
        $(window).on('load', function () {
            $('#statusMessage').modal('show');
        });
    </script>
}

AutoService.WEB/Views/ContactInfo/Index.cshtml
@model AutoService.WEB.Models.ContactView
@{
    ViewBag.Title = "Контактная информация";
}

    <h2 class="display-4 text-center">
        Контактная информация
        @if (User.IsInRole("Admin"))
        {
            <a class="btn btn-dark" href="@Url.Action("EditContacts", "ContactInfo")">
                <i class="fa fa-gear fa-lg"></i>
            </a>
        }
    </h2>

<div class="row d-flex">
    <div class="col-xl-7 col-sm-12 ml-xl-auto mr-sm-0 ml-sm-0 p-1">
        <div class="m-3 text-center">
            <iframe src="@Model.YandexFrameSrc" class="w-100 h-100" frameborder="1" allowfullscreen="true" style="min-height:400px"></iframe>
            <div class="input-group text-center m-1 mx-auto" title="Адрес">
                <div class="input-group-prepend">
                    <div class="input-group-text text-center">
                        <i class="fa fa-map-marker"></i>
                    </div>
                </div>
                <div class="form-control">
                    @Model.Address
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-4 p-3">
        <dl class="text-md-center text-xl-left text-sm-center">
            <dt class="h4">Мы в соц сетях</dt>
            <dd>
                <a class="mr-2" href="@Model.VKHref"><img title="VK" src="@Model.VKImageHref" height="70" width="70"></a>
                <a class="mr-2" href="@Model.FacebookHref"><img title="Facebook" src="@Model.FacebookImageHref" height="70" width="70"></a>
                <a class="mr-2" href="@Model.InstagramHref"><img title="Instagram" src="@Model.InstagramImageHref" height="70" width="70"></a>
            </dd>
            <dt class="h4">
                <i class="fa fa-phone-square"></i> Телефоны
            </dt>
            <dd>
                @foreach (var item in Model.ContactPhones)
                {
                    <p>@item</p>
                }
            </dd>
            <dt class="h4">
                <i class="fa fa-envelope-square"></i> Почта
            </dt>
            <dd>
                @foreach (var item in Model.ContactEmails)
                {
                    <a style="color:black" href="mailto:@item">@item</a><br />
                }
            </dd>
        </dl>
    </div>
</div>

AutoService.WEB/Views/ContactInfo/RemoveItemModalView.cshtml
@{
    ViewBag.Title = "Подтверждение удаления элемента";
}

@using AutoService.WEB.Models
@model ContactItem

<div class="modal-content">
    <!-- Заголовок модального окна -->
    <div class="modal-header">
        <h5 class="modal-title">Вы уверенны, что хотите удалить указанную контактную информацию?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <!-- Основное содержимое модального окна -->
    <div class="modal-body">
        <div>
            <div class="m-1 mb-3">
                <label class="font-weight-bold m-0"><i class="fa fa-bookmark mr-1 p-1"></i>Тип информации:</label><br />
                @Html.DisplayFor(model => model.Name)
            </div>
            <div class="m-1 mb-3">
                <label class="font-weight-bold m-0"><i class="fa fa-sticky-note mr-1 p-1"></i>Содержание:</label><br />
                @Html.DisplayFor(model => model.Value)
            </div>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="modal-footer ">
            <button class="btn btn-outline-danger" type="submit"><i class="mr-1 p-1 fa fa-trash"></i>Удалить</button>
            <button type="button" class="btn btn-dark" data-dismiss="modal"><i class="mr-1 p-1 fa fa-window-close fa-lg"></i>Закрыть</button>
        </div>
    }
</div>